### PR TITLE
Fix race condition in JenkinsTriggerHelper

### PR DESCRIPTION
**Pull request by Veske**
Fix race condition in JenkinsTriggerHelper

### CODE REVIEW

**Comment by khmarbaise** [comment]
I have checked the build it's not your fault the failing build....

**Comment by Veske** [comment]
Alright, I don't have the options currently to set-up the environment to run your IT tests also. Will wait till you guys can figure it out then.

**Comment by khmarbaise** [comment]
So the problem was a fix which failed an integration tests which was an wrong implementation...which is now fixed...

**Comment by Veske** [comment]
I might have messed up the PR, includes your changes also. Can you check it it's okay? Also if you could advice me on how to run these IT tests then I could maybe write an IT for this also later. Right now I wrote it "blindly".

**Comment by khmarbaise** [comment]
You can the IT's simply by using: `mvn -Prun-docker-its clean verify` But you need to start the docker container in the sub project `jenkins-client-it-docker` first (and run the script build-docker.sh first and afterwards start-docker.sh) ...You need of course Docker(version 1.12 recommended) installed on your machine...

BTW: Currently I'm trying to make that more simpler, cause I find it too complex as well...But the travis build already says everything looks ok...

I assume you did something wrong while you tried to do the rebase...
Simply can be done in your branch:
`git rebase master`

This will integrate all changes from the master which have been committed after you have created your branch...in the end a `git log -1` should show only your single commit...you have made..Afterwards you need to do a `git push --force origin BRANCH` which will push that back...

**Comment by khmarbaise** [comment]
Looks fine so far, cause I got only a fast-forward pull...No problem.

**Comment by Veske** [comment]
I mean the method it self, that it works. Not at work currently, have nothing to test against. Did look ok tough.

**Comment by khmarbaise** [comment]
Updated the ReleaseNotes with a hint to your GitHub reference. Thanks for your pull request.

**Comment by khmarbaise** [comment]
Can you now close the PR...

**Comment by Veske** [comment]
Umh... It's closed now, no?

**Comment by khmarbaise** [comment]
Ah sorry..missed that it is already closed. Sorry..

**Pull request merged**
