### PR TITLE
Fixed #360

### LINKED ISSUE #360: Enhancement: add Fluent-API to relevant setters in the model classes
The setters in the model classes (i.e. BaseModel, Build, Job etc) should follow the Fluent-API pattern and return the object itself instead of void to allow the client calls like "artifact.setJenkinsServer(server).setClient(client);"

### PR DESCRIPTION
**Pull request by mivola**
- changing the return value of getters from void to the appropriate object in the model classes

### CODE REVIEW

**Comment by mivola** [comment]
@khmarbaise I've seen you had been working on some issues in the past few days - could you maybe also have a look at my pull requests?

**Comment by khmarbaise** [comment]
I will try...can you check the conflicts...

**Comment by mivola** [comment]
I'd like to work on the conflicts. The problem is: how to get the changes from your (the upstream) repo to my fork? I tried various ways (https://help.github.com/en/articles/syncing-a-fork, https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser) but it always ends up with a merge - which is something you do not want IIRC... 
Any suggestions?

**Comment by mivola** [comment]
I just created a new PR (#403) to avoid cluttering the git repo. Maybe you could merge this before any other changes?

**Pull request closed without merging**
