### PR TITLE
methods with folders do use an absolute url

### PR DESCRIPTION
**Pull request by RainerW**
In our environment we need to access the jenkins (test) instance which an url that ist not the actual external url. So the jenkins server configuration does contain an external url the client cannot resolve. 
This did work because the client setup had the correct url and until now the lib used relative urls, honored the client setup url. But when using folders, the getFoldersJob() etc call does use job.getUrl() from a job instance previously retrived, which contains a 'wrong' external url! 

so this requests contains:
 * DISCLAIMER : also contains fixes for #203 because i based it on the refactorings from there
 * added getFolderJob(String) to retrive a FolderJob instance based on a folderPath (recursively) 
 * the method return null in case this is not a folder, which i think matches the getJob() contract better

### CODE REVIEW

**Comment by RainerW** [comment]
fixed the tests, not sure how to trigger the testrun again.

**Comment by RainerW** [comment]
For testing i also added return Values to all build* methods ( fixes #103 ).

**Comment by khmarbaise** [comment]
Can you please rebase with current master, cause I have merged some of your changes into master. Furthermore can you squash your commits and it would be helpful if you could fix/improve/add only a single issue in a pull request...Thanks for your support...

**Comment by khmarbaise** [comment]
See #203

**Pull request closed without merging**
