### PR TITLE
Fixed #276: Support to trigger a parameterized build with file parameters

### LINKED ISSUE #276: how to use java-client-api to trigger the job with File parameters?
I found that it only support string parameters.

### PR DESCRIPTION
**Pull request by zxq1002**
Support to trigger a parameterized build with file parameters

### CODE REVIEW

**Comment by dellgreen** [comment]
This is a great, much needed feature, however this pull request breaks public contract on some existing public methods, which may be the reason this pull request has not been accepted yet?
Maybe a refactor and overloading of existing public methods might be a better approach? :)

**Comment by khmarbaise** [comment]
Maybe I miss a thing here but where is the api broken by this PR ? Apart from that we are running 0.X release..?

**Comment by dellgreen** [comment]
Hopefully I am interpreting the diff correctly, but the addition of Map<String, File> fileParams to the public "post" method on a public class, seems to change/break the contract of this method and hence breaks any projects that currently use it. Do you not think it better to overload the method as its adding a new feature, to avoid such breakages?
Apologies in advance if I have missed something.

**Comment by zxq1002** [comment]
Well, I think the PR didn't broke any public api, only added some new function with file parameter..

**Comment by zxq1002** [comment]
Well, I think the PR didn't broke any public api, only added some new method with file parameter..

**Comment by zxq1002** [comment]
Do  I must  overload the  post  method with file  parameter?
I thought the method was  used only in this project  before, so  I modify it simply..

**Comment by dellgreen** [comment]
Apologies, i'm not seeing  the addition of a new function in JenkinsHttpClient.java, but an existing public 'post' method having its parameters changed. if JenkinsHttpClient was a package private class then it wouldn't be an issue

**Comment by zxq1002** [comment]
I have overloaded the post method to support jobs with file parameters. I'm sorry to fix it too late.  :)

**Pull request merged**
